spring:
  cache.type: none
  devtools.restart.enabled: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${JDBC_DATABASE_URL}:5432/${JDBC_DATABASE_NAME}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:

      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      org.hibernate.envers.audit_table_prefix: AUD_
      org.hibernate.envers.audit_table_suffix: null
  h2.console:
    enabled: true
    path: /db
  messages:
    basename: i18n/messages
    encoding: ISO-8859-1
  servlet.multipart:
      max-file-size: 15MB
      max-request-size: 15MB
